package issac.demo.model;

import java.math.BigDecimal;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
	private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.salary
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.descn
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.salary
     *
     * @return the value of user_info.salary
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.salary
     *
     * @param salary the value for user_info.salary
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.descn
     *
     * @return the value of user_info.descn
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.descn
     *
     * @param descn the value for user_info.descn
     *
     * @mbggenerated Tue Sep 06 21:51:55 CST 2016
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }

	@Override
	public String toString() {
		return "UserInfo [id=" + id + ", name=" + name + ", salary=" + salary + ", sex=" + sex + ", descn=" + descn + "]";
	}
}