package issac.demo.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.salary
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.descn
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private String descn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.photo
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.createTime
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.salary
     *
     * @return the value of user_info.salary
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.salary
     *
     * @param salary the value for user_info.salary
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.descn
     *
     * @return the value of user_info.descn
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.descn
     *
     * @param descn the value for user_info.descn
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.photo
     *
     * @return the value of user_info.photo
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.photo
     *
     * @param photo the value for user_info.photo
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.createTime
     *
     * @return the value of user_info.createTime
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.createTime
     *
     * @param createtime the value for user_info.createTime
     *
     * @mbggenerated Mon Sep 12 15:12:59 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}