package issac.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import issac.demo.common.IPage;
import issac.demo.model.UserInfo;

public interface UserInfoMapper extends IPage {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 09 14:03:22 CST 2016
     */
    int updateByPrimaryKey(UserInfo record);

	List<UserInfo> selectAll();
	
	List<UserInfo> getList(@Param("name") String name);
	
	List<UserInfo> getPageList(@Param("start") Integer start, @Param("end") Integer end, @Param("name") String name);

	int getTotal(@Param("name") String name);
}